language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq
install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
script:
  - make
  - make debug
  - make test
  - make example
