language: c
compiler:
  - gcc
  - clang
os:
  - linux
script:
  - make
  - make debug
  - make test
  - make example
addons:
  coverity_scan:
    project:
      name: "roel0/dividi"
      description: "Build submitted via Travis CI"
    notification_email: roel.postelmans@altran.com
    build_command:   "make && make debug"
    branch_pattern: coverity_scan
